# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HaruGominClone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HaruGominClone
#  pod 'KakaoSDKUser'
#  pod 'KakaoSDKAuth'
#  pod 'naveridlogin-sdk-ios'
  pod 'Tabman', '~> 2.9'
  pod 'Kingfisher'
  pod 'lottie-ios'
  pod "AlignedCollectionViewFlowLayout"
  pod 'SnapKit', '~> 5.0.0'
end
